# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:46:58+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class ChartPostRequest(BaseModel):
    backgroundColor: Optional[str] = Field(
        None, description='The background color of the chart.'
    )
    chart: Optional[Dict[str, Any]] = Field(
        None, description='The chart configuration in JSON format.'
    )
    format: Optional[str] = Field(
        None,
        description="The output format of the chart, e.g., 'png', 'jpg', 'svg', or 'webp'.",
    )
    height: Optional[int] = Field(
        None, description='The height of the chart in pixels.'
    )
    width: Optional[int] = Field(None, description='The width of the chart in pixels.')


class QrPostRequest(BaseModel):
    format: Optional[str] = Field(
        None, description="The output format of the QR code, e.g., 'png' or 'svg'."
    )
    height: Optional[int] = Field(
        None, description='The height of the QR code in pixels.'
    )
    margin: Optional[int] = Field(
        None, description='The margin around the QR code in pixels.'
    )
    text: Optional[str] = Field(
        None, description='The text to be encoded in the QR code.'
    )
    width: Optional[int] = Field(
        None, description='The width of the QR code in pixels.'
    )
